cases:
  - id: ethereum_lstm_36s_block300_quartile_eval
    base:
      evaluator: block_poisson_replay_300
      evaluations: ethereum_pectra_jun20_block300_quartile
      artifact_id: art_c433194c8699a301f7c5
      corpus_id: cor_7bea5a071afaf090c05a
      batch_size: 256
    steps:
      - id: evaluate_baseline
        workflow: evaluate

  - id: polygon_lstm_36s_block300_quartile_eval
    base:
      evaluator: block_poisson_replay_300
      evaluations: polygon_bhilai_large_lstm_block300_quartile
      artifact_id: art_9cdfcc1f75aadb355673
      corpus_id: cor_61fb33e47c948a9cebd0
      batch_size: 256
    steps:
      - id: evaluate_baseline
        workflow: evaluate

  - id: avalanche_lstm_36s_block300_quartile_eval
    base:
      evaluator: block_poisson_replay_300
      evaluations: avalanche_octane_large_lstm_block300_quartile
      artifact_id: art_4a91b895e756192c4106
      corpus_id: cor_3ef359c91addcab77e9f
      batch_size: 256
    steps:
      - id: evaluate_baseline
        workflow: evaluate
